## What do you want your fake journal to be called?
journal_name: Annals Of Psychoceramics B
publisher_name: CrossRef
site_uri: annalsofpsychoceramics.labs.crossref.org
description: Subscription based publisher that requires separate TDM license via Prospect License Registry and who uses rate-limits 

## What features do you want turned on?
## Comments/uncomment below as needed.
#
# OA publishers probably want:
#check_license_registry: false
#open_access: true

# Subscription publishers who allow TDM in
# exisitng institutional licenses probably want:
#check_license_registry: false
#open_access: false

# Subscription publishers who have supplementary TDM
# licenses registered with the Prospect License Registry
# probably want:

check_license_registry: true
force_ssl: false
open_access: false
accepted_licenses: [ "http://www.crossref.org/tdm_license","http://www.crossref.org/tdm_license_v2" ]
license_trust_length: 300
prospect_publisher_api_token: MdvA59fGn8ukykYlSxJL6g


# Are you worried your site might fall over
# if overburdened by TDM bots?
# NB: The numbers below are absurdly low
rate_limit: true
window_query_limit: 5
window_length: 60 


